name: 'makensis'
description: 'Nullsoft scriptable install system action'
inputs:
  script-file:
    description: 'Path to the .nsi script file.'
    required: true
    default: 'install.nsi'

  arguments:
    description: 'Arguments to makensis.exe'
    required: false
    default: ''

  just-include:
    description: 'Should we just include Nsis as an environment variable without executing?'
    required: true
    default: false

  include-more-plugins:
    description: 'Should we also add more Nsis plugins to the plugin folder?'
    required: true
    default: false
    
  include-custom-plugins-path:
    description: "If you want include additional plugins that aren't in our default directory, you could specify your plugin directory so your plugins will copied and used into NSIS process. This will work with plugins/x86-ansi."
    required: false
    default: ''

outputs:
  nsis-path:
    description: 'The path to where NSIS is installed'

runs:
  using: 'node12'
  main: 'index.js'

branding:
  icon: 'triangle'
  color: 'blue'
