name: Node.js CI

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-20.04', 'macos-latest' ]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 'Install makensis (apt)'
      run: sudo apt update && sudo apt install -y nsis nsis-pluginapi
      if: ${{ matrix.os == 'ubuntu-20.04' }}

    - name: 'Install makensis (homebrew)'
      run: brew update && brew install makensis
      if: ${{ matrix.os == 'macos-latest' }}

    - run: npm test
      if: ${{ matrix.os == 'windows-latest' }}

    - run: sudo npm test
      if: ${{ matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest' }}
